version: '3'
services:
  builder:
    image: mikebell/eleventy:0.8.3
    command: npm install
    command: eleventy
    volumes:
      - .:/usr/src
  serve:
    image: mikebell/eleventy:0.8.3
    command: npm install
    command: eleventy --serve
    volumes:
      - .:/usr/src